### ISSUE TITLE
Allow for marketplace bids in layer 1 currencies (ETH, MATIC, Avalanche)

### ISSUE THREAD

**Issue by gotechnolabs** [nftlabs/nftlabs-protocols#104]
Hi there,

Following the tutorial for creating a marketplace and am trying to create a bid as described here: https://nftlabs.github.io/nftlabs-sdk-ts/sdk.marketplacemodule.createauctionlisting.html

```
// Data of the auction you want to create
const auction = {
  // address of the contract the asset you want to list is on
  assetContractAddress: "0x...",
  // token ID of the asset you want to list
  tokenId: "0",
  // in how many seconds with the listing open up
  startTimeInSeconds: 0,
  // how long the listing will be open for
  listingDurationInSeconds: 86400,
  // how many of the asset you want to list
  quantity: 1,
  // address of the currency contract that will be used to pay for the listing
  currencyContractAddress: "0x0000000000000000000000000000000000000000",
  // how much people would have to bid to instantly buy the asset
  buyoutPricePerToken: "10",
  // the minimum bid that will be accepted for the token
  reservePricePerToken: "1",
}

await module.createAuctionListing(auction);
```
 I get that `currencyContractAddress` takes an ERC20 contract address to pay with. My question is can we add the feature to pay with raw ETH (and similarly on other coins as well). I can use wrapped ETH fine but it is annoying for users to pay gas to swap in order to buy.

Thank you for your consideration.

**Comment by gotechnolabs** [comment]
I saw this line in that PR referenced above
```
    /// @dev The address interpreted as native token of the chain.
    address public constant nativeToken = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

````

So is it as simple as passing in that address as the `currencyContractAddress` for paying with raw ETH?

**Comment by jakeloo** [comment]
Yup!
