### ISSUE TITLE
Fix restrictedTransfer on drop and (maybe) bundle drop

### ISSUE THREAD

**Issue by adam-maj** [nftlabs/nftlabs-protocols#76]
When a drop contract has restrictedTransfer set to true, you can still transfer the tokens on open sea

Here's the related PR: https://github.com/nftlabs/console/pull/423

Here's a discord message with more info: https://discord.com/channels/922584461680443402/922627376330973265/92486322661

<img width="854" alt="Screen Shot 2021-12-26 at 11 17 59 PM" src="https://user-images.githubusercontent.com/64697628/147433917-fe31936f-1e67-4973-9ef6-634a3aec7f12.png">

**Comment by nkrishang** [comment]
The transfer is valid behaviour.

When transfers are restricted on the contract (any of our contracts that have this capability), a transfer goes through on if either the from or to have transfer role.

In the [linked transaction](https://polygonscan.com/tx/0x5ee249794ae84d92657f8cb2e263628883ff9a008c0a0208af239beff2e92b6c#eventlog), the `to` address (i.e. the receiver in the transfer) has transfer role on the contract.

The following is the snippet that defines this behaviour in the `_beforeTokenTransfer` hook our ERC 1155 or 721 contracts that have the feature of restricted transfers --

```
// if transfer is restricted on the contract, we still want to allow burning and minting
        if (transfersRestricted && from != address(0) && to != address(0)) {
            require(hasRole(TRANSFER_ROLE, from) || hasRole(TRANSFER_ROLE, to), "restricted to TRANSFER_ROLE holders");
        }
```

Feel free to re-open the issue if you wish for this behaviour to be changed.
