### ISSUE TITLE
Add 0x0dEaD as burn address

### ISSUE THREAD

**Issue by nachoiacovino** [nftlabs/nftlabs-protocols#93]
https://opensea.io/BurnAddress (0x000000000000000000000000000000000000dead) is much more common to burn NFTs than https://opensea.io/NullAddress (0x0000000000000000000000000000000000000000)

We should support both.

**Comment by jakeloo** [comment]
they're served as 2 different purposes.  in general, the standard around burning is that it'd reduce the supply too and most contracts have null address designated as burning.
you can optionally transfer to 0x...dead if you wish to and use `burn()` to send the token to 0x0000s
